config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  devise_for :users
  resources :users
  resources :category
  resources :transactions

  get '/about', to: 'static_pages#about', as: 'about_page'
  get '/report/new', to: 'reports#new', as: 'new_report'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  enum flow: [:income, :expense]
  validates :name,
    presence: true,
    length: { minumum: 3, maximum: 250 }

  validates :flow,
    presence: true,
    uniqueness: { scope: [:user_id, :flow], message: 'name already in use' }
  validates :user, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy

  def amount
    self.transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  default_scope -> { order(event_date: :desc) }

  before_save :check_date
  before_create :check_balance
  around_save :check_update

  belongs_to :category
  belongs_to :user

  validates :amount, presence: true, numericality: { greater_than: 0 } 
  validates :category, presence: true
  validates :description, presence: true
  validates :event_date, presence: true
  validates :user_id, presence: true
  validates :category_id, presence: true

  self.per_page = 10

  private 
  	def check_balance
      if self.category.flow == "expense"
        if self.user.balance(format: false).to_f - self.amount < 0
          self.errors.add(:amount, "is too large")
          throw(:abort)
        end
      end
  	end

    def check_date
      current = Date.current
      if self.event_date > current
        self.errors.add(:event_date, "must be less or equal current date")
        throw(:abort)
      end
    end

    def check_update
      yield
      if self.user.balance(format: false) < 0
        self.amount = self.amount_was
        self.errors.add(:amount, "is invalid. Balance can't be less that zero.")
        raise ActiveRecord::Rollback
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories, dependent: :destroy
  has_many :transactions, through: :categories, source: :transactions

  def name
  	self.email.split('@')[0]
  end


  def income(date: Date.current, last_include: false)
    if last_include
  	   self.categories.income.joins(:transactions).where("event_date <= ?", date).sum(:amount)
    else
        self.categories.income.joins(:transactions).where("event_date < ?", date).sum(:amount)
    end
  end

  def expense(date: Date.current, last_include: false)
    if last_include
      self.categories.expense.joins(:transactions).where("event_date <= ?", date).sum(:amount)
    else
      self.categories.expense.joins(:transactions).where("event_date < ?", date).sum(:amount)
    end
  end

  def balance(format: true, date: Date.current, last_include: true)
    balance = (income(date: date, last_include: last_include) - expense(date: date, 
                                                                last_include: last_include))
  	if format
      "%.2f" % balance
    else
      balance
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include UsersHelper
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :authenticate_user!
  before_action :get_catagories
  before_action :get_category, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    run Category::Present
  end

  def create
    run Category::Create do |op|
      flash[:success] = 'Category was added'
      return redirect_to category_index_path
    end

    render :index
#    @category = current_user.categories.new(category_params)
#    if @category.save
#      flash[:success] = "Category was added"
#      redirect_to category_index_path
#    else
#      render "index"
#    end
  end


  def edit
  end

  def update
    save = @category.update_attributes(category_params)
    if save
      flash[:success] = "Category was changed"
      redirect_to category_index_path
    else
      render "edit"
    end

  end

  def destroy
    new_balance = current_user.balance(format: false).to_f - @category.amount
    if @category.flow == "income" and new_balance < 0
      flash[:danger] = "Operation was not perform. Balance can't be less than zero."
      redirect_to category_index_path
    else
      @category.destroy
      flash[:success] = "Category was removed"
      redirect_to category_index_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:flow, :name)  
  end

  def get_catagories
    @categories = current_user.categories.all
  end

  def get_category
    @category = Category.find(params[:id])
  end

  def check_user
    if !current_user?(@category.user)
      redirect_to root_path
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
	def new
		@ready = false	

		if params[:report]
			date_from = params[:report][:from]
			date_to = params[:report][:to]

			#TODO: clean up all this rubbish
			@balance_from = current_user.balance(date: date_from, last_include: false)
			@balance_to = current_user.balance(date: date_to)

			@income = current_user.categories.income.joins(:transactions)
				.where("event_date between ? and ?", date_from, date_to)
				.group(:name).sum(:amount)

			@income_transactions = current_user.transactions
				.where("event_date between ? and ? and categories.flow = ?", date_from, date_to, 0)

			@expense = current_user.categories.expense.joins(:transactions)
				.where("event_date between ? and ?", date_from, date_to)
				.group(:name).sum(:amount)

			@expense_transactions = current_user.transactions
				.where("event_date between ? and ? and categories.flow = ?", date_from, date_to, 1)

			@ready = true
		end	
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		if user_signed_in?
			redirect_to transactions_path
		end
	end


	def about
		
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_categories, only: [:index, :edit, :update, :create]
  before_action :get_transaction, only: [:destroy, :edit, :update]
  before_action :get_transactions, only: [:index, :create]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @transaction = Transaction.new(event_date: Time.zone.now, amount: 1)
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = @transaction.category.user
    if @transaction.save
      flash[:success] = "Transaction was added."
      redirect_to transactions_path
    else
      render "index"
    end
  end

  def edit

  end

  def update
    if @transaction.update_attributes(transaction_params)
      flash[:success] = "Transaction was updated"
      redirect_to transactions_path
    else
      render "edit"
    end
  end

  def destroy
    flow = @transaction.category.flow
    new_balance = current_user.balance(format: false).to_f - @transaction.amount
    if flow == "income" and new_balance < 0
        flash[:danger] = "Operation was not perform. Balance can't be less than zero."
        redirect_to transactions_path
    else
      @transaction.destroy
      flash[:success] = "Transaction was removed."
      redirect_to transactions_path
    end
  end

  private
    def get_categories
      @categories = current_user.categories.all
    end

    def transaction_params
      params.require(:transaction).permit(:amount, :description, :category_id, :event_date)
    end

    def get_transaction
      @transaction = Transaction.find(params[:id])
    end

    def get_transactions
      @transactions = current_user.transactions.paginate(page: params[:page])
    end

    def check_user
      if !current_user?(@transaction.user)
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :corrent_user

	def report
		@income = current_user.categories
	end

	private

		def corrent_user
			@user = User.find(params[:id])
			redirect_to root_path unless current_user?(@user)
		end

end

app/helpers/users_helper.rb
module UsersHelper
	
	def current_user?(user)
		current_user == user		
	end

	def currency(value)
    	"%.2f $" % value
 	end
end

app/views/cashes/edit.html.erb
<% provide(:title, "Edit transaction") %>

<h1>Update your transaction</h1>

<div class="row">
	<div class="col-md-6 add-transaction">
		
		<%= render "edit_form" %>
	</div>
</div>

app/views/category/_edit_form.html.erb
<%= form_for(@category) do |f| %>
	<%= render "shared/error_messages", object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>

	<%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/category/_new_category.html.erb
<%= form_for(@form, url: category_index_path) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', placeholder: "Category name" %>

  <%= f.label :type %>
  <%= f.select :flow, [['Income', "income"], ["Expense", "expense"]], {}, {class: "form-control"} %>

  <%= f.submit "Add category", class: 'btn btn-primary' %>
<% end %>

app/views/category/edit.html.erb
<% provide(:title, "Edit category") %>

<h1>Update your category</h1>

<div class="row">
	<div class="col-md-6 offset-md-3">
		
		<%= render "edit_form" %>
	</div>
</div>

app/views/category/index.html.erb
<% provide(:title, "Categories") %>

<div class="col-md-4 col-lg-4">
  <h2>New category</h2>

  <div class="add-category">
    <%= render "new_category" %>
  </div>

</div>
<div class="col-md-8 col-lg-8">
  <h2>Categories list:</h2>

  <% if @categories.any?  %>
    <table class="table tabls-sm table-hover">
      <thead>
        <th>Name</th>
        <th>Type</th>
        <th>Amount</th>
        <th> </th>
        <th> </th>
      </thead>
      <tbody>
        <% @categories.each do |cat| %>
        <tr>
          <td>
            <%= cat.name %>
          </td>   
          <td>
            <%= cat.flow %>
          </td>
          <td>
            <%= currency(cat.amount) %>
          </td>
          <td>
              <%= link_to " ", edit_category_path(cat), class: "badge  glyphicon glyphicon-pencil" %>
          </td>
          <td>
              <%= link_to " ", category_path(cat), method: :delete, class: "badge glyphicon glyphicon-remove" %>
          </td>
        <% end %>  
        </tr>
      </tbody>
    </table>
  <% else %>
    <p>No category find</p>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="inc">
    <p>@ 2020 gmbl3r</p>
</div>
<div>
	<ul class="footer-menu">
		<li><%= link_to "About", about_page_path %></li>
	</ul>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Money Keeper</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>

                <li><%= link_to "Transactions", transactions_path %></li>
                <li><%= link_to "Categories", category_index_path %></li>
        <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><strong> (<%= current_user.balance %>$) </strong> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Report", new_report_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Profile", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
				          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
				<% else %>
				 <li><%= link_to "Sign Up", new_user_registration_path %></li>
				 <li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/_welcome.html.erb
<% provide(:title, "Money Keeper") %>

	<div class="jumbotron text-center">
		<div class="col-md-offset-5 col-lg-offset-5">
			  <h1 class="display-3">Welcome</h1>
			  <p class="lead">This simple service will help you track your money.</p>
			  <hr class="plank">
			  <p>Well, when will we start?</p>
			  <p class="lead">
						 <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %> or
			    		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
			  </p>

		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<!-- Render menu -->
  	<%= render 'layouts/menu' %>


	<!-- Render flash alerts -->
	<% if flash.any? %>
	  	<div class="container">
			<% flash.each do |key, value| %>

				<div class="alert alert-<%= key %> alert-dismissible show" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				  <%= value %>
				</div>

			<% end %>
		</div>
	<% end %>

	<!-- Main content -->
    <div class="container">
    	<%= yield %>
    </div>
    <footer  class="footer container">
		<%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/reports/_chart.html.erb
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<%= javascript_tag do %>
  $(function() {
      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});
      var income = <%= @income.to_a.to_json.html_safe %>
      var expense = <%= @expense.to_a.to_json.html_safe %>
      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawIncomeChart);
      google.charts.setOnLoadCallback(drawExpenseChart);
      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawIncomeChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();

        data.addColumn('string', 'Category');
        data.addColumn('number', 'Amount');
        data.addRows(income);

        // Set chart options
        var options = {'title':'Income', 'height': 400};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('income'));
        chart.draw(data, options);
      }

      function drawExpenseChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();

        data.addColumn('string', 'Category');
        data.addColumn('number', 'Amount');
        data.addRows(expense);

        // Set chart options
        var options = {'title':'Expense', 'height': 400};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('expense'));
        chart.draw(data, options);
      }
  });
<% end %>
    <div class="col-md-6 col-lg-6">
      <h3>Balance before: <%= @balance_from %></h3>
    </div>
    <div class="col-md-6 col-lg-6">
      <h3>Balance after: <%= @balance_to %></h3>
    </div>
    <!--Div that will hold the pie chart-->

    <div class="container">
      <div class="col-md-6 col-lg-6" id="income"></div>
      <div class="col-md-6 col-lg-6" id="expense"></div>    
    </div>

    <div class="container">
      <div class="col-md-6 col-lg-6">
        <% if @income_transactions.any?  %>
          <h2>Income transactions:</h2>
          <table class="table tabls-sm table-hover">
            <thead>
              <th>Amount</th>
              <th>Description</th>
              <th>Category</th>
              <th>Date</th>
            </thead>
            <tbody>
              <% @income_transactions.each do |trans| %>
                <tr>
                  <td>
                    <%= currency(trans.amount) %>
                  </td>
                  <td>
                    <%= trans.description %>
                  </td>
                  <td>
                    <%= trans.category.name %>
                  </td>
                  <td>
                    <%= trans.event_date %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>

      <div class="col-md-6 col-lg-6">
        <% if @expense_transactions.any?  %>
          <h2>Expense transactions:</h2>
          <table class="table tabls-sm table-hover">
            <thead>
              <th>Amount</th>
              <th>Description</th>
              <th>Category</th>
              <th>Date</th>
            </thead>
            <tbody>
              <% @expense_transactions.each do |trans| %>
                <tr>
                  <td>
                    <%= currency(trans.amount) %>
                  </td>
                  <td>
                    <%= trans.description %>
                  </td>
                  <td>
                    <%= trans.category.name %>
                  </td>
                  <td>
                    <%= trans.event_date %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>

app/views/reports/new.html.erb
<% provide(:title, "Report page") %>
<div class="container">
	<%= form_for :report, url: new_report_path, method: :get, html: {class: "form-inline report-form"} do |f|%>
		<%= f.label :from %>
		<%= f.date_field :from, value: Date.current, class: "form-control" %>

		<%= f.label :to %>
		<%= f.date_field :to, value: Date.current, class: "form-control" %>

		<%= f.submit "Get report", class: "btn btn-primary" %>
	<% end %>
	
</div>

<% if @ready == true %>
	<div class="container">
		<%= render "chart" %>
	</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% unless object.errors.empty? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h2>Money Keeper</h2>

<p>Just another useless page.</p>
<p>I have nothing to say</p>

<p>If you do please contact me via <a href="https://github.com/Casilio">github</a>.</p>

app/views/static_pages/index.html.erb
<%= render 'layouts/welcome' %>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :transaction_amount %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_select :event_date, id: :transaction_event_date %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :transaction_category_id %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :transaction_user %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_new_transaction.html.erb
<%= form_for(@transaction) do |f| %>
	<%= render "shared/error_messages", object: f.object %>

	<%= f.label :amount, "Amount ($)" %>
	<%= f.number_field :amount, value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), step: :any, class: "form-control" %>

	<%= f.label :description %>
	<%= f.text_field :description, class: "form-control", placeholder: "Description" %>

	<%= f.label :date %>
	<%= f.date_field :event_date, class: "form-control" %>

	<%= f.label :Category %>
	<%= f.select :category_id, @categories.collect{ |c| [ "#{c.name} (#{c.flow})", c.id ]}, {}, {class: "form-control"} %>

	<div>
		<%= f.submit yield(:button), class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/transactions/edit.html.erb
<% provide(:title, "Edit transaction") %>

<h1>Update your transaction</h1>

<div class="row">
	<div class="col-md-6 add-transaction">
		<% provide(:button, "Save") %>
		<%= render "new_transaction" %>
	</div>
</div>

app/views/transactions/index.html.erb
<% provide(:title, "Transactions") %>

<div class="col-md-4 col-lg-4">
	<h2>New transaction</h2>

	<% if @categories.any? %>
		<div class="add-transaction">
			<% provide(:button, "Add transaction") %>
			<%= render "new_transaction" %>
		</div>
	<% else %>
		<p>First you could add <%= link_to "category", category_index_path %></p>
	<% end %>
</div>

<div class="col-md-8 col-lg-8">
	<h2>Transactions list:</h2>

		<table class="table tabls-sm table-hover">
			<thead>
				<th>Amount</th>
				<th>Description</th>
				<th>Category</th>
				<th>Date</th>
				<th> </th>
				<th> </th>
			</thead>
			<tbody>
		<% if @transactions.any?  %>
			<% @transactions.each do |trans| %>
				<tr>
					<td>
						<%= currency(trans.amount) %>
					</td>   
					<td>
						<%= trans.description %>
					</td>
					<td>
						<%= "#{trans.category.name}(#{trans.category.flow})" %>
					</td>
					<td>
						<%= trans.event_date %>
					</td>
					<td>
					    <%= link_to " ", transaction_path(trans), method: :delete, class: "badge glyphicon glyphicon-remove" %>
					</td>
					<td>
					    <%= link_to " ", edit_transaction_path(trans), class: "badge  glyphicon glyphicon-pencil" %>
					</td>
				</tr>
			<% end %>
		<% else %>
			<tr>
				<td>Empty</td>
			</tr>
		<% end %>
			</tbody>
		</table>
			<%= will_paginate @transactions, renderer: BootstrapPagination::Rails %>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @transaction.event_date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>